#classification tree model-ebay exercise
install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)

ebay.df <- read.csv("eBayAuctions.csv")
View(ebay.df)
#1. Split the data into training and validation datasets using a 65% to 35% ratio, with a seed of 333.
set.seed(333)
train.index <- sample(1:nrow(ebay.df), nrow(ebay.df)*0.65)
train.df <- ebay.df[train.index, ]
valid.df <- ebay.df[-train.index, ]
#2. Fit a classification tree using all predictors. Use the default tree generated by rpart().
#Apply this default tree on validation set and write down the confusion matrix. 
#How can you compute the accuracy based on the confusion matrix?
library(ggplot2)
library(caret)


default2.ct <- rpart(Competitive ~ ., data = train.df, method = "class", control = rpart.control(maxdepth = 3, minbucket = 30))
prp(default2.ct, type=1, extra=1)
full.ct <- rpart(Competitive ~ ., data = train.df, method = "class", control= rpart.control(cp= -1, minsplit = 1))  #full tree

default2.ct.point.pred <- predict(default2.ct, valid.df, type = "class" )
# generate confusion matrix for validation data
confusionMatrix(default2.ct.point.pred, factor(valid.df$Competitive))

#3 Find the accuracy of this model for training data.
default2.train.pred <- predict(default2.ct, train.df, type = "class")
confusionMatrix(default2.train.pred, factor(train.df$Competitive))

#4 Is this model practical for predicting the outcome of a new auction? 
# (HINT: Consider the availability of information about the predictors at the time of prediction.)

# No, close price is not available at the time of decision.

#5
#select vars:
selected.var <- c(1,2,3,4,6,7)  
selected.train.df <- train.df[, selected.var]








